### ISSUE TITLE
IBusOutboxNotification is not registered in DI container in CustomEntityFrameworkBusOutboxConfigurator

### ISSUE THREAD

**Issue by hongliyu2002** [fluxera/Fluxera.Extensions.Hosting.Modules#102]
When I run my application, I find the following error:
```csharp
System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHost
edService Lifetime: Singleton ImplementationType: MassTransit.EntityFrameworkCoreIntegration.BusOutboxDeliveryService`1[MassVending.Snacks.Infrastructure.Contexts.Snac
kDbContext]': Unable to resolve service for type 'MassTransit.Middleware.Outbox.IBusOutboxNotification' while attempting to activate 'MassTransit.EntityFrameworkCoreIn
tegration.BusOutboxDeliveryService`1[MassVending.Snacks.Infrastructure.Contexts.SnackDbContext]'.) (Error while validating the service descriptor 'ServiceType: MassTra
nsit.DependencyInjection.IScopedBusContextProvider`1[MassTransit.IBus] Lifetime: Scoped ImplementationType: MassTransit.EntityFrameworkCoreIntegration.EntityFrameworkS
copedBusContextProvider`2[MassTransit.IBus,MassVending.Snacks.Infrastructure.Contexts.SnackDbContext]': Unable to resolve service for type 'MassTransit.Middleware.Outb
ox.IBusOutboxNotification' while attempting to activate 'MassTransit.EntityFrameworkCoreIntegration.EntityFrameworkScopedBusContextProvider`2[MassTransit.IBus,MassVend
ing.Snacks.Infrastructure.Contexts.SnackDbContext]'.)
```
I found that it was caused by IBusOutboxNotification in Fluxera.Extensions.Hosting.Modules.Messaging.Outbox.EntityFrameworkCore not being registered in the DI Container, I checked your source code and compared the MassTransit related source code and found only one discrepancy: 
_configurator.AddSingleton<IBusOutboxNotification, BusOutboxNotification>().

Please check:
[https://github.com/fluxera/Fluxera.Extensions.Hosting.Modules/blob/main/src/Fluxera.Extensions.Hosting.Modules.Messaging.Outbox. EntityFrameworkCore/CustomEntityFrameworkBusOutboxConfigurator.cs](url)
And
[https://github.com/MassTransit/MassTransit/blob/master/src/Persistence/MassTransit.EntityFrameworkCoreIntegration/Configuration/Configuration/EntityFrameworkBusOutboxConfigurator.cs](url)

I have a little confusing, your CustomEntityFrameworkBusOutboxConfigurator / EntityFrameworkBusOutboxConfigurator, and CustomEntityFrameworkOutboxConfigurator / EntityFrameworkOutboxConfigurator are almost identical, why do you need to write a custom one?

**Comment by mgernand** [comment]
Hi! 

Thanks again for this find. I fixed the inbox/outbox configuration for EF Core and MongoDB. The sample application is new configured to use EF Core.

The custom configurator classes where left-over from an expreoment to implement inbox/outbox für multi-tenant applications that use the database-per-tenant approach. The ```InboxCleanupService```and ```BusOutboxDeliveryService``` lack the information about the current tenant of a request. This may not be a big problem when using one database for all tenants using a discriminator column, but when using separate databases it becomes a big one. The custom classes are now removed.

I plan to implement those services in the future supporting multi-tenant applications that use the database-per-tenant approach. But fpor now this only worlds without multi-tenancy enabled or with one shared database.

See: #81

**Comment by hongliyu2002** [comment]
You're right, this Outbox pattern is related, it's goal is to use the same database transaction to ensure that no message is sent on a save changes failure, and it does require some code rewriting in the case of multi-tenant databases

**Comment by mgernand** [comment]
The problem with multi-tenancy with database-per-tenant and the outbox is that the cleanup and delivery services must handle all those different connection information from all tenants. So right now, if you have a multi-tenant application, you can use multi-tenancy with a discriminator column in the same one database, or disable the outbox if you don't need it. 

If you need the oubox feature of MassTransit and use database-per-tenant then you have to implement custom ```InboxCleanupService```and ```BusOutboxDeliveryService``` that iterates all available databases an then cleans or delivers messages from those.
