### ISSUE TITLE
Fluxera.Extensions.Hosting.Modules.Messaging.RabbitMQ module has a bug

### ISSUE THREAD

**Issue by hongliyu2002** [fluxera/Fluxera.Extensions.Hosting.Modules#99]
HealthChecksContributor and TransportContributor share the same connection string name, but the connection string format is different, which prevents the correct connection to RabbitMQ.

**Comment by hongliyu2002** [comment]
Personally, I think I just need to rewrite the RabbitMqConnectionString class:
```csharp
	internal sealed class RabbitMqConnectionString
	{
		public RabbitMqConnectionString(string connectionString)
		{
			Guard.Against.NullOrWhiteSpace(connectionString, nameof(connectionString));

			// amqps://admin:admin@localhost/
			var uri = new Uri(connectionString);
			if (uri.Scheme != "amqps")
			{
				throw new ArgumentException("Invalid connection string scheme. Scheme must be 'amqps'.", nameof(connectionString));
			}
			this.Host = uri.Host;
			this.Username = Uri.UnescapeDataString(uri.UserInfo.Split(':')[0]);
			this.Password = Uri.UnescapeDataString(uri.UserInfo.Split(':')[1]);
		}

		public string Host { get; } = "localhost";

		public string Username { get; } = "guest";

		public string Password { get; } = "guest";
	}
```

**Comment by mgernand** [comment]
Hi, thank you for reporting this.

The issues was that the connection string for the health check was not correctly built from the ```RabbitMqConnectionString``` instance. I fixed this in the latest version. The RabbitMQ connection string must be configured in ``appsettings.json``` in teh following format:

```plain
Host=localhost;Username=guest;Password=guest;
```

The conenction URI for the health check isthen built in the ```RabbitMqConnectionString``` class and passed onto the health check.
